# Generated by Django 3.2.4 on 2022-03-10 10:46

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='users_subscriptions_constrains',
        ),
        migrations.AlterField(
            model_name='advuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email адрес'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='show_email',
            field=models.BooleanField(default=True, verbose_name='Email скрыт?'),
        ),
        migrations.AlterField(
            model_name='social',
            name='image',
            field=models.FilePathField(blank=True, path='static/images/social'),
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(('sub_on', django.db.models.expressions.F('user')), _negated=True), name='users_subscriptions_constrains'),
        ),
    ]
