# Generated by Django 3.2.4 on 2022-02-27 14:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('headline', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('sub_headline', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст поста')),
                ('featured', models.BooleanField(default=False, verbose_name='Опубликовать сразу?')),
                ('active', models.BooleanField(default=False, verbose_name='Активен?')),
                ('likes', models.IntegerField(blank=True, default=0, verbose_name='Количество просмотров')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тег')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
