# Generated by Django 3.2.4 on 2022-02-26 11:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тег')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('headline', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('sub_headline', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст поста')),
                ('featured', models.BooleanField(default=False, verbose_name='Опубликован?')),
                ('active', models.BooleanField(default=False, verbose_name='Активен?')),
                ('likes', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
                ('tags', models.ManyToManyField(null=True, to='blog.Tags')),
            ],
        ),
    ]
